export const BUSINESS_TEMPLATES = {
  restaurant: {
    type: 'restaurant',
    icon: '🍛',
    label: 'Indian Restaurant',
    config: {
      name: 'Desi Road Restaurant',
      tagline: 'Elevated Indian Cuisine',
      city: 'Brampton',
      phone: '(437) 331-5615',
      location: '185 Fletchers Creek Blvd, Brampton',
      hours: 'Mon-Sat 11am-11pm, Sun 12pm-10pm',
      brand_tagline: 'Desi Daru Desi Khana',
      special_name: 'Shahi Lamb Chops',
      special_desc: 'discounted price tonight',
      monthly_price: '$599',
      logo_url: 'https://desiroad.ca/wp-content/uploads/2016/10/DESI-ROAD-LOGO-1.jpg',
      menu: [
        { name: 'Butter Chicken Cones', price: 16.99, category: 'main' },
        { name: 'Shahi Lamb Chops', price: 29.99, category: 'main' },
        { name: 'Dal Makhani', price: 15.99, category: 'main' },
        { name: 'Palak Paneer', price: 14.99, category: 'main' },
        { name: 'Chicken Biryani', price: 18.99, category: 'main' },
        { name: 'Garlic Naan', price: 3.99, category: 'bread' },
        { name: 'Mango Lassi', price: 5.99, category: 'drink' },
        { name: 'Gulab Jamun', price: 6.99, category: 'dessert' },
      ],
    },
    quickMsgs: [
      { text: 'Butter Chicken please', label: '🍛 Butter Chicken' },
      { text: 'Lamb Chops', label: '🍖 Lamb Chops' },
      { text: 'What is the menu?', label: '📋 Menu' },
    ],
    presentation: {
      problem: {
        eyebrow: 'Step 1 — The Opportunity',
        title: ['is losing orders', 'every single night.'],
        desc: 'When the phone rings at 10pm and the kitchen is busy. When a Punjabi customer WhatsApps and gets no reply until morning.',
        stats: [
          { value: '73%', label: 'Never call back if nobody answers first time', color: 'red' },
          { value: '10pm', label: 'Peak hour when orders are lost to voicemail', color: 'gold' },
          { value: '30%', label: 'Commission Uber Eats takes per order', color: 'red' },
          { value: '$0', label: 'Revenue from missed calls and messages', color: 'gold' },
        ],
        flows: [
          { icon: '📞', title: 'Phone rings at 10pm', desc: 'Staff are busy. Nobody answers. Customer calls a different restaurant.' },
          { icon: '💬', title: 'WhatsApp at 9pm — no reply', desc: 'Customer orders Uber Eats — Uber keeps 30%.' },
          { icon: '🗣️', title: 'Multilingual customer messages', desc: 'No staff who speak that language. Customer never hears back.' },
        ],
      },
      solution: {
        eyebrow: 'Step 2 — The Solution',
        title: ['Every order. Every language.', 'Every hour.'],
        desc: 'Your existing phone and WhatsApp — completely unchanged. Zivio AI handles everything silently behind it, 24/7.',
        stats: [
          { value: '24/7', label: 'Orders taken — even midnight and holidays', color: 'green' },
          { value: '3', label: 'Languages auto-detected', color: 'gold' },
          { value: '20+', label: 'Simultaneous conversations', color: 'green' },
          { value: '$0', label: 'Commission per order', color: 'gold' },
        ],
        flows: [
          { num: '1', title: 'Customer contacts you — same number', desc: 'Nothing changes for the customer.' },
          { num: '2', title: 'AI detects language, responds instantly', desc: 'Punjabi, Hindi, English — matched naturally.' },
          { num: '3', title: 'Takes the full order and confirms', desc: 'Remembers returning customers.' },
          { num: '4', title: 'Alert goes to your team instantly', desc: 'Full formatted ticket in 3 seconds.' },
        ],
      },
      features: [
        { icon: '📞', title: '24/7 Phone Ordering', desc: 'AI answers in 2 rings. Takes full order, confirms.', tag: 'Voice AI' },
        { icon: '💬', title: 'WhatsApp Ordering', desc: 'On your existing number.', tag: 'Existing Number' },
        { icon: '🗣️', title: '3 Languages Auto-detect', desc: 'English, Punjabi, Hindi + code-switching.', tag: 'Multilingual' },
        { icon: '🧠', title: 'Customer Memory', desc: 'Remembers returning customers and their favorites.', tag: 'Loyalty' },
        { icon: '🔔', title: 'Instant Alerts', desc: 'Every order to your team in 3 seconds.', tag: 'Real-time' },
        { icon: '📢', title: 'Daily Campaigns', desc: 'Broadcast specials to your subscriber list.', tag: 'Marketing' },
        { icon: '⭐', title: 'Review Automation', desc: 'Happy customer → review request. Unhappy → owner alert.', tag: 'Reputation' },
      ],
      compare: {
        competitors: ['Uber Eats', 'DoorDash'],
        rows: [
          ['Monthly fee', '$0', '$0', '$599 flat'],
          ['Commission per order', '25–35%', '25–30%', '0%'],
          ['You own the customer', '✗', '✗', '✓'],
          ['Multilingual support', '✗', '✗', '✓'],
          ['24/7 ordering', '✗', '✗', '✓'],
        ],
      },
      pricing: { amount: '$599', period: '/month CAD · First month free · No contract' },
    },
  },

  dentist: {
    type: 'dentist',
    icon: '🦷',
    label: 'Dental Clinic',
    config: {
      name: 'Bright Smile Dental',
      tagline: 'Family Dentistry & Cosmetic Care',
      city: 'Brampton',
      phone: '(437) 331-5615',
      location: '220 Queen St E, Brampton',
      hours: 'Mon-Fri 8am-6pm, Sat 9am-3pm',
      brand_tagline: 'Your Smile, Our Priority',
      special_name: 'Free Teeth Whitening Consultation',
      special_desc: 'this month only',
      monthly_price: '$599',
      logo_url: '',
      menu: [
        { name: 'Regular Checkup & Cleaning', price: 199, category: 'preventive' },
        { name: 'Teeth Whitening', price: 349, category: 'cosmetic' },
        { name: 'Dental Filling', price: 175, category: 'restorative' },
        { name: 'Root Canal', price: 850, category: 'restorative' },
        { name: 'Crown & Bridge', price: 1200, category: 'restorative' },
        { name: 'Emergency Visit', price: 150, category: 'emergency' },
        { name: 'X-Ray (Full Mouth)', price: 120, category: 'diagnostic' },
        { name: 'Invisalign Consultation', price: 0, category: 'cosmetic' },
      ],
    },
    quickMsgs: [
      { text: 'I need to book a cleaning', label: '🪥 Book Cleaning' },
      { text: 'Emergency — tooth pain', label: '🚨 Emergency' },
      { text: 'What are your hours?', label: '🕐 Hours' },
    ],
    presentation: {
      problem: {
        eyebrow: 'Step 1 — The Opportunity',
        title: ['is losing patients', 'to unanswered calls.'],
        desc: 'When the phone rings during a procedure, no one can answer. Patients call the next clinic. Every missed call is a lost patient — potentially for life.',
        stats: [
          { value: '62%', label: 'Of patients won\'t leave a voicemail', color: 'red' },
          { value: '35%', label: 'Of calls come during lunch or after hours', color: 'gold' },
          { value: '$500+', label: 'Lifetime value of one lost patient', color: 'red' },
          { value: '0', label: 'Online bookings after hours', color: 'gold' },
        ],
        flows: [
          { icon: '📞', title: 'Patient calls during procedure', desc: 'Front desk is busy. Call goes to voicemail. Patient books elsewhere.' },
          { icon: '💬', title: 'WhatsApp at 8pm — no reply', desc: 'Patient needed an emergency appointment. Goes to walk-in clinic.' },
          { icon: '🗣️', title: 'Non-English speaker calls', desc: 'Can\'t communicate their issue. Gives up and doesn\'t come back.' },
        ],
      },
      solution: {
        eyebrow: 'Step 2 — The Solution',
        title: ['Every patient. Every call.', 'Every language.'],
        desc: 'Zivio AI answers your clinic phone and WhatsApp 24/7 — books appointments, handles emergencies, speaks their language.',
        stats: [
          { value: '24/7', label: 'Appointment booking — even weekends', color: 'green' },
          { value: '3', label: 'Languages — English, Punjabi, Hindi', color: 'gold' },
          { value: '< 3s', label: 'Response time to every patient', color: 'green' },
          { value: '0', label: 'Missed calls, ever', color: 'gold' },
        ],
        flows: [
          { num: '1', title: 'Patient contacts your clinic', desc: 'Same number. Nothing changes for them.' },
          { num: '2', title: 'AI books appointment instantly', desc: 'Checks availability, confirms date and time.' },
          { num: '3', title: 'Emergency? Routes immediately', desc: 'Urgent cases get flagged and routed to the dentist.' },
          { num: '4', title: 'Reminder sent automatically', desc: 'Reduces no-shows by 40%.' },
        ],
      },
      features: [
        { icon: '📞', title: '24/7 Appointment Booking', desc: 'AI books appointments anytime — even 11pm Sunday.', tag: 'Voice AI' },
        { icon: '💬', title: 'WhatsApp Scheduling', desc: 'Patients text to book. Instant confirmation.', tag: 'Convenience' },
        { icon: '🗣️', title: 'Multilingual Support', desc: 'English, Punjabi, Hindi — auto-detected.', tag: 'Brampton-ready' },
        { icon: '🚨', title: 'Emergency Triage', desc: 'AI identifies urgent cases and alerts you immediately.', tag: 'Safety' },
        { icon: '🔔', title: 'Appointment Reminders', desc: 'Auto-remind patients. Reduce no-shows by 40%.', tag: 'Retention' },
        { icon: '⭐', title: 'Review Requests', desc: 'Happy patient → Google review request automatically.', tag: 'Reputation' },
      ],
      compare: {
        competitors: ['Receptionist', 'Voicemail'],
        rows: [
          ['Availability', '8am-5pm', '24/7 (no booking)', '24/7 + booking'],
          ['Cost/month', '$3,500+', '$0', '$599'],
          ['Multilingual', 'Sometimes', '✗', '✓'],
          ['Books appointments', '✓', '✗', '✓'],
          ['Never sick/late', '✗', '✓', '✓'],
        ],
      },
      pricing: { amount: '$599', period: '/month CAD · First month free · No contract' },
    },
  },

  pharmacy: {
    type: 'pharmacy',
    icon: '💊',
    label: 'Pharmacy',
    config: {
      name: 'MedCare Pharmacy',
      tagline: 'Your Neighbourhood Pharmacy',
      city: 'Brampton',
      phone: '(437) 331-5615',
      location: '55 Queen St W, Brampton',
      hours: 'Mon-Sat 9am-9pm, Sun 10am-6pm',
      brand_tagline: 'Care Beyond the Counter',
      special_name: 'Free Flu Shot',
      special_desc: 'walk-in, no appointment needed',
      monthly_price: '$599',
      logo_url: '',
      menu: [
        { name: 'Prescription Refill', price: 0, category: 'rx' },
        { name: 'New Prescription Transfer', price: 0, category: 'rx' },
        { name: 'Flu Shot', price: 0, category: 'vaccine' },
        { name: 'COVID Booster', price: 0, category: 'vaccine' },
        { name: 'Blood Pressure Check', price: 0, category: 'service' },
        { name: 'Medication Review', price: 0, category: 'service' },
        { name: 'Blister Packaging', price: 15, category: 'service' },
        { name: 'Compression Stocking Fitting', price: 45, category: 'service' },
      ],
    },
    quickMsgs: [
      { text: 'I need to refill my prescription', label: '💊 Refill Rx' },
      { text: 'Do you have flu shots?', label: '💉 Flu Shot' },
      { text: 'Transfer my prescription', label: '📋 Transfer' },
    ],
    presentation: {
      problem: {
        eyebrow: 'Step 1 — The Opportunity',
        title: ['is losing refills', 'to unanswered calls.'],
        desc: 'Pharmacists are busy compounding. The phone rings. Nobody picks up. Patient goes to Shoppers Drug Mart.',
        stats: [
          { value: '45%', label: 'Of pharmacy calls go unanswered during peak', color: 'red' },
          { value: '$200+', label: 'Annual value of one lost patient', color: 'gold' },
          { value: '60%', label: 'Of refills could be handled by AI', color: 'red' },
          { value: '0', label: 'After-hours refill requests processed', color: 'gold' },
        ],
        flows: [
          { icon: '📞', title: 'Patient calls for refill', desc: 'Pharmacist is with another patient. Call missed. Patient goes elsewhere.' },
          { icon: '💬', title: 'WhatsApp request at 8pm', desc: 'Need meds before tomorrow. No response until morning.' },
          { icon: '🗣️', title: 'Elderly patient calls', desc: 'Confused about medication. Can\'t get through. Misses doses.' },
        ],
      },
      solution: {
        eyebrow: 'Step 2 — The Solution',
        title: ['Every refill. Every question.', 'Every language.'],
        desc: 'Zivio AI handles prescription refills, answers medication questions, and manages your phone — 24/7.',
        stats: [
          { value: '24/7', label: 'Refill requests accepted', color: 'green' },
          { value: '< 5s', label: 'Response to every patient', color: 'gold' },
          { value: '60%', label: 'Less phone burden on pharmacists', color: 'green' },
          { value: '$0', label: 'Per-refill cost', color: 'gold' },
        ],
        flows: [
          { num: '1', title: 'Patient contacts pharmacy', desc: 'Phone or WhatsApp — same number as always.' },
          { num: '2', title: 'AI takes refill request', desc: 'Rx number, name, or medication — AI handles it.' },
          { num: '3', title: 'Pharmacist gets formatted request', desc: 'Ready to process, no phone tag.' },
          { num: '4', title: 'Patient notified when ready', desc: 'Auto WhatsApp: "Your prescription is ready for pickup!"' },
        ],
      },
      features: [
        { icon: '💊', title: '24/7 Refill Requests', desc: 'AI takes Rx refills anytime.', tag: 'Core' },
        { icon: '💬', title: 'WhatsApp Refills', desc: 'Text your Rx number. Done.', tag: 'Convenience' },
        { icon: '🗣️', title: 'Multilingual', desc: 'English, Punjabi, Hindi.', tag: 'Community' },
        { icon: '🔔', title: 'Ready Notifications', desc: 'Patient notified instantly when Rx ready.', tag: 'Alerts' },
        { icon: '📋', title: 'Transfer Handling', desc: 'AI collects info for pharmacy transfers.', tag: 'Growth' },
        { icon: '⭐', title: 'Review Requests', desc: 'Auto Google review after great service.', tag: 'Reputation' },
      ],
      compare: {
        competitors: ['Phone Tag', 'IVR System'],
        rows: [
          ['Availability', 'Store hours only', '24/7 (robotic)', '24/7 (natural)'],
          ['Multilingual', '✗', '✗', '✓'],
          ['Takes refills', 'Sometimes', '✗', '✓'],
          ['Patient notification', '✗', '✗', '✓'],
          ['Monthly cost', '$0 (staff time)', '$200+', '$599'],
        ],
      },
      pricing: { amount: '$599', period: '/month CAD · First month free · No contract' },
    },
  },

  pizza: {
    type: 'pizza',
    icon: '🍕',
    label: 'Pizza Store',
    config: {
      name: 'Slice House Pizza',
      tagline: 'Hand-Tossed, Wood-Fired',
      city: 'Brampton',
      phone: '(437) 331-5615',
      location: '88 Main St N, Brampton',
      hours: 'Mon-Sun 11am-12am',
      brand_tagline: 'Real Pizza, Real Fast',
      special_name: 'Large Pepperoni + Wings Combo',
      special_desc: '$24.99 tonight only',
      monthly_price: '$599',
      logo_url: '',
      menu: [
        { name: 'Large Pepperoni Pizza', price: 16.99, category: 'pizza' },
        { name: 'Large Margherita', price: 14.99, category: 'pizza' },
        { name: 'BBQ Chicken Pizza', price: 18.99, category: 'pizza' },
        { name: 'Veggie Supreme', price: 15.99, category: 'pizza' },
        { name: 'Chicken Wings (12pc)', price: 14.99, category: 'sides' },
        { name: 'Garlic Bread', price: 5.99, category: 'sides' },
        { name: 'Caesar Salad', price: 7.99, category: 'sides' },
        { name: '2L Pop', price: 3.49, category: 'drink' },
      ],
    },
    quickMsgs: [
      { text: 'Large pepperoni pizza', label: '🍕 Pepperoni' },
      { text: 'Wings combo deal', label: '🍗 Wings Combo' },
      { text: 'What deals do you have?', label: '💰 Deals' },
    ],
    presentation: {
      problem: {
        eyebrow: 'Step 1 — The Opportunity',
        title: ['is losing orders', 'every Friday night.'],
        desc: 'Phone rings non-stop on weekends. Staff juggling dough, oven, and phone. Orders get lost. Customers switch to Skip or Uber.',
        stats: [
          { value: '40%', label: 'Of calls missed during Friday rush', color: 'red' },
          { value: '30%', label: 'Commission on every app order', color: 'gold' },
          { value: '$8K+', label: 'Lost to delivery apps monthly', color: 'red' },
          { value: '0', label: 'Direct orders after midnight', color: 'gold' },
        ],
        flows: [
          { icon: '📞', title: 'Phone rings during Friday rush', desc: 'Staff hands full of dough. Customer gets busy tone, orders Skip.' },
          { icon: '💬', title: '11pm text order', desc: 'Nobody sees it until morning. $50 order gone.' },
          { icon: '🔄', title: 'Regular orders same thing weekly', desc: 'Has to repeat full order every time. Slows everything down.' },
        ],
      },
      solution: {
        eyebrow: 'Step 2 — The Solution',
        title: ['Every order. Zero commission.', 'Zero missed calls.'],
        desc: 'Zivio AI takes phone and WhatsApp orders 24/7. Your staff focuses on making great pizza.',
        stats: [
          { value: '24/7', label: 'Orders — even 2am on Sunday', color: 'green' },
          { value: '0%', label: 'Commission — flat fee only', color: 'gold' },
          { value: '< 3s', label: 'Every call answered', color: 'green' },
          { value: '100%', label: 'You keep the customer', color: 'gold' },
        ],
        flows: [
          { num: '1', title: 'Customer calls or texts', desc: 'Same number — AI picks up instantly.' },
          { num: '2', title: 'Takes the full order', desc: 'Size, toppings, sides, drinks — all handled.' },
          { num: '3', title: 'Kitchen gets the ticket', desc: 'Printed or WhatsApp alert. Ready to make.' },
          { num: '4', title: 'Customer picks up, you keep 100%', desc: 'No app. No commission. No middleman.' },
        ],
      },
      features: [
        { icon: '📞', title: '24/7 Phone Orders', desc: 'AI takes orders even during Friday rush.', tag: 'Core' },
        { icon: '💬', title: 'WhatsApp Ordering', desc: 'Text to order. Instant confirmation.', tag: 'Convenience' },
        { icon: '🧠', title: 'Regular Memory', desc: '"Same as last Friday?" One-tap reorder.', tag: 'Loyalty' },
        { icon: '🔔', title: 'Kitchen Tickets', desc: 'Order to kitchen printer in 3 seconds.', tag: 'Speed' },
        { icon: '📢', title: 'Deal Blasts', desc: 'Send tonight\'s deal to 500 subscribers.', tag: 'Marketing' },
        { icon: '⭐', title: 'Review Requests', desc: 'Auto Google review after delivery.', tag: 'Reputation' },
      ],
      compare: {
        competitors: ['Uber Eats', 'Skip The Dishes'],
        rows: [
          ['Commission', '30%', '25%', '0%'],
          ['Monthly cost', '$0', '$0', '$599'],
          ['$30 order — you keep', '~$21', '~$22.50', '$30.00'],
          ['Own the customer', '✗', '✗', '✓'],
          ['24/7 phone ordering', '✗', '✗', '✓'],
        ],
      },
      pricing: { amount: '$599', period: '/month CAD · First month free · No contract' },
    },
  },

  doctor: {
    type: 'doctor',
    icon: '🩺',
    label: "Doctor's Clinic",
    config: {
      name: 'CarePlus Medical Clinic',
      tagline: 'Family Medicine & Walk-In',
      city: 'Brampton',
      phone: '(437) 331-5615',
      location: '150 Central Park Dr, Brampton',
      hours: 'Mon-Fri 8am-7pm, Sat 9am-2pm',
      brand_tagline: 'Healthcare That Listens',
      special_name: 'Same-Day Appointments',
      special_desc: 'available for urgent needs',
      monthly_price: '$599',
      logo_url: '',
      menu: [
        { name: 'General Consultation', price: 0, category: 'visit' },
        { name: 'Walk-In Appointment', price: 0, category: 'visit' },
        { name: 'Annual Physical', price: 0, category: 'preventive' },
        { name: 'Prescription Renewal', price: 0, category: 'service' },
        { name: 'Blood Work Requisition', price: 0, category: 'diagnostic' },
        { name: 'Referral Request', price: 0, category: 'service' },
        { name: 'Sick Note / Medical Letter', price: 25, category: 'document' },
        { name: 'Travel Vaccination', price: 75, category: 'vaccine' },
      ],
    },
    quickMsgs: [
      { text: 'I need to see a doctor today', label: '🩺 Same Day' },
      { text: 'Renew my prescription', label: '💊 Rx Renewal' },
      { text: 'Book annual physical', label: '📋 Physical' },
    ],
    presentation: {
      problem: {
        eyebrow: 'Step 1 — The Opportunity',
        title: ['is losing patients', 'to hold times.'],
        desc: 'Patients call and wait on hold. Front desk is overwhelmed. Simple requests like Rx renewals clog the phone. Patients leave for clinics that answer.',
        stats: [
          { value: '8 min', label: 'Average hold time at family clinics', color: 'red' },
          { value: '55%', label: 'Hang up after 2 minutes on hold', color: 'gold' },
          { value: '40%', label: 'Of calls are simple requests (Rx, referrals)', color: 'red' },
          { value: '$800+', label: 'Lifetime value per patient lost', color: 'gold' },
        ],
        flows: [
          { icon: '📞', title: 'Patient calls for appointment', desc: 'On hold 10 minutes. Gives up. Goes to walk-in down the street.' },
          { icon: '💬', title: 'Needs prescription renewal', desc: 'Simple request but requires calling during business hours. Patient frustrated.' },
          { icon: '🗣️', title: 'Elderly patient, language barrier', desc: 'Can\'t explain symptoms in English. Delays care.' },
        ],
      },
      solution: {
        eyebrow: 'Step 2 — The Solution',
        title: ['Every patient heard.', 'Zero hold time.'],
        desc: 'Zivio AI handles bookings, Rx renewals, and basic inquiries — freeing your staff to focus on patient care.',
        stats: [
          { value: '0 sec', label: 'Wait time for patients', color: 'green' },
          { value: '24/7', label: 'Booking available', color: 'gold' },
          { value: '40%', label: 'Fewer phone calls to front desk', color: 'green' },
          { value: '3', label: 'Languages supported', color: 'gold' },
        ],
        flows: [
          { num: '1', title: 'Patient calls or messages', desc: 'AI answers instantly. Zero hold time.' },
          { num: '2', title: 'Books appointment or takes request', desc: 'Same-day, regular, or Rx renewal.' },
          { num: '3', title: 'Front desk gets notification', desc: 'Organized request, ready to process.' },
          { num: '4', title: 'Patient gets confirmation', desc: 'Appointment confirmed. Reminder sent automatically.' },
        ],
      },
      features: [
        { icon: '📞', title: '24/7 Booking', desc: 'AI books appointments anytime.', tag: 'Core' },
        { icon: '💊', title: 'Rx Renewal Requests', desc: 'Patients request renewals by text/call.', tag: 'Efficiency' },
        { icon: '🗣️', title: 'Multilingual', desc: 'English, Punjabi, Hindi.', tag: 'Community' },
        { icon: '🔔', title: 'Appointment Reminders', desc: 'Reduce no-shows by 40%.', tag: 'Retention' },
        { icon: '📋', title: 'Referral & Sick Notes', desc: 'AI collects details, staff processes.', tag: 'Admin' },
        { icon: '⭐', title: 'Patient Satisfaction', desc: 'Auto-survey after visits.', tag: 'Quality' },
      ],
      compare: {
        competitors: ['Front Desk Only', 'IVR System'],
        rows: [
          ['Hold time', '5-15 min', '2-5 min (robotic)', '0 seconds'],
          ['After-hours booking', '✗', '✗', '✓'],
          ['Multilingual', 'Sometimes', '✗', '✓'],
          ['Rx renewals by text', '✗', '✗', '✓'],
          ['Monthly cost', '$3,500+ (staff)', '$300', '$599'],
        ],
      },
      pricing: { amount: '$599', period: '/month CAD · First month free · No contract' },
    },
  },

  trades: {
    type: 'trades',
    icon: '🔧',
    label: 'Skilled Trades',
    config: {
      name: 'ProFix Home Services',
      tagline: 'Plumbing, Electrical & HVAC',
      city: 'Brampton',
      phone: '(437) 331-5615',
      location: 'Serving all of Brampton & Mississauga',
      hours: 'Mon-Sat 7am-9pm, Emergency 24/7',
      brand_tagline: 'We Fix It Right',
      special_name: 'Free Furnace Inspection',
      special_desc: 'with any service booking this month',
      monthly_price: '$599',
      logo_url: '',
      menu: [
        { name: 'Plumbing Service Call', price: 89, category: 'plumbing' },
        { name: 'Drain Cleaning', price: 149, category: 'plumbing' },
        { name: 'Water Heater Install', price: 1200, category: 'plumbing' },
        { name: 'Electrical Panel Upgrade', price: 2500, category: 'electrical' },
        { name: 'Light Fixture Install', price: 120, category: 'electrical' },
        { name: 'Furnace Repair', price: 250, category: 'hvac' },
        { name: 'AC Install', price: 3500, category: 'hvac' },
        { name: 'Emergency Call (24/7)', price: 149, category: 'emergency' },
      ],
    },
    quickMsgs: [
      { text: 'I have a leaking pipe', label: '🔧 Plumbing' },
      { text: 'Furnace not working', label: '🔥 HVAC' },
      { text: 'Need an electrician', label: '⚡ Electrical' },
    ],
    presentation: {
      problem: {
        eyebrow: 'Step 1 — The Opportunity',
        title: ['is losing jobs', 'to missed calls.'],
        desc: 'You\'re on a job site. Phone rings. Hands are dirty. By the time you call back, they\'ve booked someone else.',
        stats: [
          { value: '80%', label: 'Of customers hire the first person who answers', color: 'red' },
          { value: '$350', label: 'Average job value lost per missed call', color: 'gold' },
          { value: '6pm+', label: 'Most emergency calls come after hours', color: 'red' },
          { value: '$0', label: 'Revenue from calls you missed on-site', color: 'gold' },
        ],
        flows: [
          { icon: '📞', title: 'Customer calls while you\'re on a job', desc: 'Can\'t answer. They call the next plumber on Google.' },
          { icon: '💬', title: 'Emergency text at 10pm', desc: 'Burst pipe. You see it at 7am. They already called someone else.' },
          { icon: '🔄', title: 'Repeat customer needs service', desc: 'Calls twice, no answer. Books a competitor.' },
        ],
      },
      solution: {
        eyebrow: 'Step 2 — The Solution',
        title: ['Every call answered.', 'Every job booked.'],
        desc: 'Zivio AI answers your phone 24/7 — books jobs, handles emergencies, quotes estimates. You focus on the work.',
        stats: [
          { value: '24/7', label: 'Every call answered', color: 'green' },
          { value: '< 3s', label: 'Response time', color: 'gold' },
          { value: '3x', label: 'More jobs booked per month', color: 'green' },
          { value: '$0', label: 'You miss zero calls', color: 'gold' },
        ],
        flows: [
          { num: '1', title: 'Customer calls or texts', desc: 'AI picks up instantly, collects details.' },
          { num: '2', title: 'AI gathers job information', desc: 'What\'s the issue? Address? Photos? Urgency?' },
          { num: '3', title: 'You get the job alert', desc: 'Full details on your phone. Accept or schedule.' },
          { num: '4', title: 'Customer confirmed', desc: 'AI sends confirmation and estimated arrival.' },
        ],
      },
      features: [
        { icon: '📞', title: '24/7 Call Answering', desc: 'Never miss a job. AI answers every call.', tag: 'Core' },
        { icon: '💬', title: 'WhatsApp Booking', desc: 'Customers text to book. Instant response.', tag: 'Convenience' },
        { icon: '🚨', title: 'Emergency Routing', desc: 'Urgent calls flagged and sent to you immediately.', tag: 'Safety' },
        { icon: '🧠', title: 'Job Details Collection', desc: 'AI gets photos, address, issue description.', tag: 'Efficiency' },
        { icon: '🔔', title: 'Job Alerts', desc: 'Instant notification with full job details.', tag: 'Speed' },
        { icon: '⭐', title: 'Review Requests', desc: 'Auto Google review after job completion.', tag: 'Reputation' },
      ],
      compare: {
        competitors: ['Answering Service', 'Voicemail'],
        rows: [
          ['Availability', '9am-5pm', '24/7 (no booking)', '24/7 + booking'],
          ['Books jobs', '✗', '✗', '✓'],
          ['Collects details', 'Basic', '✗', 'Full + photos'],
          ['Emergency routing', '✗', '✗', '✓'],
          ['Monthly cost', '$500+', '$0', '$599'],
        ],
      },
      pricing: { amount: '$599', period: '/month CAD · First month free · No contract' },
    },
  },
};

export const BUSINESS_TYPE_LIST = Object.values(BUSINESS_TEMPLATES);
